import { Conduce, Region, EstadoBulto } from '@/types/conduces';

// Mock signature in SVG data URL format for demo purposes
const DEMO_SIGNATURE = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="300" height="150" viewBox="0 0 300 150"><path d="M 20 80 Q 50 20, 80 70 T 140 60 T 200 85 T 260 50" fill="none" stroke="%231e3a8a" stroke-width="3" stroke-linecap="round"/><path d="M 60 100 Q 120 120, 240 95" fill="none" stroke="%231e3a8a" stroke-width="2" stroke-linecap="round"/><text x="30" y="130" font-family="sans-serif" font-size="12" fill="%236b7280">Firma Recibido: Dr. R. Santos</text></svg>';

function formatDate(date: Date): string {
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
}

export function generateDemoConduces(): Conduce[] {
  const today = new Date();
  
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);

  const twoDaysAgo = new Date(today);
  twoDaysAgo.setDate(today.getDate() - 2);

  const threeDaysAgo = new Date(today);
  threeDaysAgo.setDate(today.getDate() - 3);

  const fiveDaysAgo = new Date(today);
  fiveDaysAgo.setDate(today.getDate() - 5);

  const lastMonth = new Date(today);
  lastMonth.setMonth(today.getMonth() - 1);
  lastMonth.setDate(15);

  const demoList: Conduce[] = [
    // ----------------------------------------------------
    // REGIÓN NORTE
    // ----------------------------------------------------
    {
      id: 'demo-c-101',
      numeroConduce: '8093101',
      numeroFactura: 'F-94101',
      numeroCliente: '10421',
      razonSocial: 'FARMACIA SAN RAFAEL',
      ciudad: 'Santiago de los Caballeros',
      ubicacion: 'Av. Juan Pablo Duarte #45, Santiago',
      cantidadBultos: 4,
      cantidadEntregados: 4,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '10:30 AM',
      tiempoEntrega: '1h 45m',
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Santiago Centro',
      relacion: 'Relación Norte 01',
      nota: 'Entregado en almacén farmacéutico conforme.',
      firma: DEMO_SIGNATURE,
      prioridad: false
    },
    {
      id: 'demo-c-102',
      numeroConduce: '8093102',
      numeroFactura: 'F-94102',
      numeroCliente: '10422',
      razonSocial: 'CENTRO MÉDICO DR. BOURNIGAL',
      ciudad: 'Puerto Plata',
      ubicacion: 'Calle Antera Mota #12, Puerto Plata',
      cantidadBultos: 6,
      cantidadEntregados: 6,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '11:15 AM',
      tiempoEntrega: '2h 10m',
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Costa Norte',
      relacion: 'Relación Norte 01',
      nota: 'Recibido por Lic. Almonte con sello.',
      firma: DEMO_SIGNATURE,
      prioridad: true
    },
    {
      id: 'demo-c-103',
      numeroConduce: '8093103',
      numeroFactura: 'F-94103',
      numeroCliente: '10423',
      razonSocial: 'FARMACIA LOS JARDINES METROPOLITANA',
      ciudad: 'Santiago',
      ubicacion: 'Av. Metropolitana #88, Los Jardines',
      cantidadBultos: 3,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Santiago Este',
      relacion: 'Relación Norte 01',
      nota: 'En ruta de entrega matutina.',
      prioridad: false
    },
    {
      id: 'demo-c-104',
      numeroConduce: '8093104',
      numeroFactura: 'F-94104',
      numeroCliente: '10424',
      razonSocial: 'DROGUERÍA CENTRAL DEL CIBAO',
      ciudad: 'La Vega',
      ubicacion: 'Calle Restauración #20, La Vega',
      cantidadBultos: 8,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-05',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta La Vega - Bonao',
      relacion: 'Relación Norte 02',
      nota: 'Carga prioritaria refrigerada.',
      prioridad: true
    },
    {
      id: 'demo-c-105',
      numeroConduce: '8093105',
      numeroFactura: 'F-94105',
      numeroCliente: '10425',
      razonSocial: 'FARMACIA BELLO HORIZONTE',
      ciudad: 'San Francisco de Macorís',
      ubicacion: 'Calle Castillo #50, San Francisco',
      cantidadBultos: 5,
      cantidadEntregados: 5,
      estado: 'Entregado',
      fechaCarga: formatDate(yesterday),
      fechaEntrega: formatDate(yesterday),
      horaEntregaExacta: '02:40 PM',
      tiempoEntrega: '3h 15m',
      encomendado: 'R-05',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Nordeste',
      relacion: 'Relación Norte 02',
      nota: 'Entregado satisfactoriamente.',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-106',
      numeroConduce: '8093106',
      numeroFactura: 'F-94106',
      numeroCliente: '10426',
      razonSocial: 'FARMACIA SAN JUDAS TADEO MOCA',
      ciudad: 'Moca',
      ubicacion: 'Calle Independencia #14, Moca',
      cantidadBultos: 2,
      cantidadEntregados: 2,
      estado: 'Entregado',
      fechaCarga: formatDate(yesterday),
      fechaEntrega: formatDate(yesterday),
      horaEntregaExacta: '04:10 PM',
      tiempoEntrega: '1h 50m',
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Moca - Salcedo',
      relacion: 'Relación Norte 01',
      nota: 'Firmado por encargado de turno.',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-107',
      numeroConduce: '8093107',
      numeroFactura: 'F-94107',
      numeroCliente: '10427',
      razonSocial: 'CLÍNICA UNIÓN MÉDICA DEL NORTE',
      ciudad: 'Santiago',
      ubicacion: 'Av. 27 de Febrero #23, Santiago',
      cantidadBultos: 7,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Clínicas Santiago',
      relacion: 'Relación Norte 01'
    },
    {
      id: 'demo-c-108',
      numeroConduce: '8093108',
      numeroFactura: 'F-94108',
      numeroCliente: '10428',
      razonSocial: 'FARMACIA VALVERDE MAO',
      ciudad: 'Mao, Valverde',
      ubicacion: 'Calle Duarte #10, Mao',
      cantidadBultos: 3,
      cantidadEntregados: 0,
      estado: 'Devuelto',
      fechaCarga: formatDate(twoDaysAgo),
      fechaEntrega: formatDate(twoDaysAgo),
      encomendado: 'R-05',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Noroeste Línea',
      relacion: 'Relación Norte 02',
      nota: 'Establecimiento cerrado por inventario.',
      excepcion: true,
      motivoExcepcion: 'Cliente cerrado al momento de visita'
    },
    {
      id: 'demo-c-109',
      numeroConduce: '8093109',
      numeroFactura: 'F-94109',
      numeroCliente: '10429',
      razonSocial: 'HOSPITAL METROPOLITANO HOMS',
      ciudad: 'Santiago',
      ubicacion: 'Autopista Duarte Km 2.8, Santiago',
      cantidadBultos: 12,
      cantidadEntregados: 12,
      estado: 'Entregado',
      fechaCarga: formatDate(threeDaysAgo),
      fechaEntrega: formatDate(threeDaysAgo),
      horaEntregaExacta: '09:45 AM',
      tiempoEntrega: '1h 30m',
      encomendado: 'R-01',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Hospitalaria',
      relacion: 'Relación Norte 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-110',
      numeroConduce: '8093110',
      numeroFactura: 'F-94110',
      numeroCliente: '10430',
      razonSocial: 'FARMACIA SANTA ROSA BONAO',
      ciudad: 'Bonao',
      ubicacion: 'Calle Duarte #55, Bonao',
      cantidadBultos: 4,
      cantidadEntregados: 4,
      estado: 'Entregado',
      fechaCarga: formatDate(lastMonth),
      fechaEntrega: formatDate(lastMonth),
      horaEntregaExacta: '03:15 PM',
      tiempoEntrega: '2h 05m',
      encomendado: 'R-05',
      region: 'Norte',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Bonao',
      relacion: 'Relación Norte 02',
      firma: DEMO_SIGNATURE
    },

    // ----------------------------------------------------
    // REGIÓN SUR
    // ----------------------------------------------------
    {
      id: 'demo-c-201',
      numeroConduce: '8093201',
      numeroFactura: 'F-94201',
      numeroCliente: '10501',
      razonSocial: 'FARMACIA SAN CRISTÓBAL CENTRAL',
      ciudad: 'San Cristóbal',
      ubicacion: 'Calle Padre Ayala #33, San Cristóbal',
      cantidadBultos: 5,
      cantidadEntregados: 5,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '10:00 AM',
      tiempoEntrega: '1h 15m',
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta San Cristóbal',
      relacion: 'Relación Sur 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-202',
      numeroConduce: '8093202',
      numeroFactura: 'F-94202',
      numeroCliente: '10502',
      razonSocial: 'CENTRO MÉDICO REGIONAL BANÍ',
      ciudad: 'Baní',
      ubicacion: 'Calle Presidente Billini #18, Baní',
      cantidadBultos: 4,
      cantidadEntregados: 4,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '12:30 PM',
      tiempoEntrega: '2h 45m',
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Baní - Ocoa',
      relacion: 'Relación Sur 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-203',
      numeroConduce: '8093203',
      numeroFactura: 'F-94203',
      numeroCliente: '10503',
      razonSocial: 'FARMACIA EL CARMEN AZUA',
      ciudad: 'Azua',
      ubicacion: 'Calle Emilio Prud-Homme #8, Azua',
      cantidadBultos: 6,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Azua Centro',
      relacion: 'Relación Sur 01'
    },
    {
      id: 'demo-c-204',
      numeroConduce: '8093204',
      numeroFactura: 'F-94204',
      numeroCliente: '10504',
      razonSocial: 'DROGUERÍA SUR SAN JUAN',
      ciudad: 'San Juan de la Maguana',
      ubicacion: 'Av. Independencia #40, San Juan',
      cantidadBultos: 7,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta El Valle',
      relacion: 'Relación Sur 01'
    },
    {
      id: 'demo-c-205',
      numeroConduce: '8093205',
      numeroFactura: 'F-94205',
      numeroCliente: '10505',
      razonSocial: 'FARMACIA CENTRAL BARAHONA',
      ciudad: 'Barahona',
      ubicacion: 'Calle Jaime Mota #22, Barahona',
      cantidadBultos: 5,
      cantidadEntregados: 5,
      estado: 'Entregado',
      fechaCarga: formatDate(yesterday),
      fechaEntrega: formatDate(yesterday),
      horaEntregaExacta: '03:50 PM',
      tiempoEntrega: '4h 10m',
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Costa Sur',
      relacion: 'Relación Sur 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-206',
      numeroConduce: '8093206',
      numeroFactura: 'F-94206',
      numeroCliente: '10506',
      razonSocial: 'BOTICA Y SALUD NEYBA',
      ciudad: 'Neyba, Bahoruco',
      ubicacion: 'Calle San Bartolomé #15, Neyba',
      cantidadBultos: 2,
      cantidadEntregados: 0,
      estado: 'Devuelto',
      fechaCarga: formatDate(twoDaysAgo),
      fechaEntrega: formatDate(twoDaysAgo),
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Bahoruco',
      relacion: 'Relación Sur 01',
      nota: 'Cambio de dirección del cliente reportado.',
      excepcion: true,
      motivoExcepcion: 'Dirección no localizada'
    },
    {
      id: 'demo-c-207',
      numeroConduce: '8093207',
      numeroFactura: 'F-94207',
      numeroCliente: '10507',
      razonSocial: 'CLÍNICA PERAVIA BANÍ',
      ciudad: 'Baní',
      ubicacion: 'Calle Mella #45, Baní',
      cantidadBultos: 8,
      cantidadEntregados: 8,
      estado: 'Entregado',
      fechaCarga: formatDate(threeDaysAgo),
      fechaEntrega: formatDate(threeDaysAgo),
      horaEntregaExacta: '11:00 AM',
      tiempoEntrega: '2h 15m',
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Baní',
      relacion: 'Relación Sur 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-208',
      numeroConduce: '8093208',
      numeroFactura: 'F-94208',
      numeroCliente: '10508',
      razonSocial: 'FARMACIA SAN JOSÉ DE OCOA',
      ciudad: 'San José de Ocoa',
      ubicacion: 'Calle 16 de Agosto #12, Ocoa',
      cantidadBultos: 3,
      cantidadEntregados: 3,
      estado: 'Entregado',
      fechaCarga: formatDate(lastMonth),
      fechaEntrega: formatDate(lastMonth),
      horaEntregaExacta: '01:20 PM',
      tiempoEntrega: '3h 00m',
      encomendado: 'R-02',
      region: 'Sur',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Ocoa Montaña',
      relacion: 'Relación Sur 01',
      firma: DEMO_SIGNATURE
    },

    // ----------------------------------------------------
    // REGIÓN ESTE
    // ----------------------------------------------------
    {
      id: 'demo-c-301',
      numeroConduce: '8093301',
      numeroFactura: 'F-94301',
      numeroCliente: '10601',
      razonSocial: 'FARMACIA LA FE LA ROMANA',
      ciudad: 'La Romana',
      ubicacion: 'Calle Castillo Márquez #10, La Romana',
      cantidadBultos: 6,
      cantidadEntregados: 6,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '11:00 AM',
      tiempoEntrega: '2h 00m',
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Romana Centro',
      relacion: 'Relación Este 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-302',
      numeroConduce: '8093302',
      numeroFactura: 'F-94302',
      numeroCliente: '10602',
      razonSocial: 'CENTRO MÉDICO PUNTA CANA',
      ciudad: 'Punta Cana / Bávaro',
      ubicacion: 'Av. España #45, Bávaro',
      cantidadBultos: 9,
      cantidadEntregados: 9,
      estado: 'Entregado',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      horaEntregaExacta: '01:45 PM',
      tiempoEntrega: '3h 30m',
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Turística Este',
      relacion: 'Relación Este 01',
      firma: DEMO_SIGNATURE,
      prioridad: true
    },
    {
      id: 'demo-c-303',
      numeroConduce: '8093303',
      numeroFactura: 'F-94303',
      numeroCliente: '10603',
      razonSocial: 'FARMACIA SAN PEDRO DE MACORÍS',
      ciudad: 'San Pedro de Macorís',
      ubicacion: 'Av. Independencia #60, San Pedro',
      cantidadBultos: 4,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta San Pedro',
      relacion: 'Relación Este 01'
    },
    {
      id: 'demo-c-304',
      numeroConduce: '8093304',
      numeroFactura: 'F-94304',
      numeroCliente: '10604',
      razonSocial: 'DROGUERÍA DEL ESTE HIGÜEY',
      ciudad: 'Higüey',
      ubicacion: 'Calle Hermanos Trejo #18, Higüey',
      cantidadBultos: 5,
      cantidadEntregados: 0,
      estado: 'En tránsito',
      fechaCarga: formatDate(today),
      fechaEntrega: formatDate(today),
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Higüey',
      relacion: 'Relación Este 01'
    },
    {
      id: 'demo-c-305',
      numeroConduce: '8093305',
      numeroFactura: 'F-94305',
      numeroCliente: '10605',
      razonSocial: 'FARMACIA CAROL BÁVARO',
      ciudad: 'Bávaro',
      ubicacion: 'Plaza San Juan #104, Bávaro',
      cantidadBultos: 4,
      cantidadEntregados: 4,
      estado: 'Entregado',
      fechaCarga: formatDate(yesterday),
      fechaEntrega: formatDate(yesterday),
      horaEntregaExacta: '04:20 PM',
      tiempoEntrega: '3h 10m',
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Bávaro',
      relacion: 'Relación Este 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-306',
      numeroConduce: '8093306',
      numeroFactura: 'F-94306',
      numeroCliente: '10606',
      razonSocial: 'HOSPITAL DR. TEÓFILO HERNÁNDEZ',
      ciudad: 'El Seibo',
      ubicacion: 'Calle Principal #2, El Seibo',
      cantidadBultos: 3,
      cantidadEntregados: 3,
      estado: 'Entregado',
      fechaCarga: formatDate(threeDaysAgo),
      fechaEntrega: formatDate(threeDaysAgo),
      horaEntregaExacta: '12:10 PM',
      tiempoEntrega: '2h 50m',
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta El Seibo - Hato Mayor',
      relacion: 'Relación Este 01',
      firma: DEMO_SIGNATURE
    },
    {
      id: 'demo-c-307',
      numeroConduce: '8093307',
      numeroFactura: 'F-94307',
      numeroCliente: '10607',
      razonSocial: 'FARMACIA HATO MAYOR CENTRAL',
      ciudad: 'Hato Mayor del Rey',
      ubicacion: 'Calle San Antonio #15, Hato Mayor',
      cantidadBultos: 2,
      cantidadEntregados: 2,
      estado: 'Entregado',
      fechaCarga: formatDate(lastMonth),
      fechaEntrega: formatDate(lastMonth),
      horaEntregaExacta: '02:00 PM',
      tiempoEntrega: '2h 15m',
      encomendado: 'R-04',
      region: 'Este',
      laboratorio: 'Laboratorio Demo',
      ruta: 'Ruta Hato Mayor',
      relacion: 'Relación Este 01',
      firma: DEMO_SIGNATURE
    }
  ];

  return demoList;
}

export function getDemoDashboardData() {
  return {
    norteBultos: 48,
    surBultos: 35,
    esteBultos: 24,
    delayedCount: 0,
    delayedConduces: [],
    recentDeliveries: [
      {
        id: 'demo-recent-1',
        numeroConduce: '8093101',
        razonSocial: 'FARMACIA SAN RAFAEL',
        cantidadBultos: 4,
        horaEntrega: '10:30 AM'
      },
      {
        id: 'demo-recent-2',
        numeroConduce: '8093201',
        razonSocial: 'FARMACIA SAN CRISTÓBAL CENTRAL',
        cantidadBultos: 5,
        horaEntrega: '10:00 AM'
      },
      {
        id: 'demo-recent-3',
        numeroConduce: '8093301',
        razonSocial: 'FARMACIA LA FE LA ROMANA',
        cantidadBultos: 6,
        horaEntrega: '11:00 AM'
      },
      {
        id: 'demo-recent-4',
        numeroConduce: '8093102',
        razonSocial: 'CENTRO MÉDICO DR. BOURNIGAL',
        cantidadBultos: 6,
        horaEntrega: '11:15 AM'
      }
    ],
    camionesStats: [
      {
        truck: 'R-01',
        clientCount: 4,
        bultos: 20,
        conduces: 4
      },
      {
        truck: 'R-02',
        clientCount: 4,
        bultos: 18,
        conduces: 4
      },
      {
        truck: 'R-04',
        clientCount: 3,
        bultos: 16,
        conduces: 3
      },
      {
        truck: 'R-05',
        clientCount: 3,
        bultos: 15,
        conduces: 3
      }
    ]
  };
}
